export const Constants = {
  StaringUp: "Starting up...",
  ServerIsListening: "Server is listening on port ",
  InternalServerError: "An unhandled error occured - Internal server error",
  EndpointNotFound: "Endpoint not found",
  BlockedByCors: "Blocked by CORS Policy. This domain doesn't have access to this server.",
  DBStoreInitialized: "Database store initialized successfully",
  FailedToDBStoreInitialized: "Failed to initialize database store",
  FailedToCreateEntity: "Failed to create entity",
  UpdateFailed: "Entity update failed",
  EntityNotFound: "Entity not found",
  InvalidRequest: "Invalid request",
  IvalidDataType: "Invalid data type",
  RequiredField: "Required field",
  StartedTask: "Started executing bacground task...",
  TaskScheduled: "Task scheduled. Task name: ",
  InvalidExp: "Invalid cron expression",
  InvalidMail: "Invalid email: ",
  MailSentTo: "Mail sent to: ",
  UsernameTaken: "Username is already taken",
  EmailTaken: "Email is already taken",
  AccountCreated: "Account created",
  AccountVerified: "Account verified",
  ServerIsOverloaded: "Server is overloaded",
  EntityCreated: "Entity created successfully",
  ServerIsTaken: "Server is taken",
  ServiceUnavailable: "Service unavailable",
  EntityAlreadyExist: "Entity already exist",
  EntityUpdated: "Entity update successfully",
  PreparingToSendMailTo: "Perparing to send mail to: ",
  TaskExecuted: "Task executed successfully. Task name: "
}